### ISSUE TITLE
Create an env.sample

### ISSUE THREAD

**Issue by peterdanwan** [jackcaunter/sigma-video-generator#3]
Currently, there is no information regarding how we should store API keys such as our [ElevenLabs](https://elevenlabs.io/docs/api-reference/text-to-speech) API key needed for text-to-speech generation.

To enhance the project such that users know how to run it, we should create an `env.sample` file that looks something like this:

```txt
ELEVENLABS_API_KEY=sk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

I'd love to work on this!

**Comment by jackcaunter** [comment]
sounds good to me boss

**Comment by jackcaunter** [comment]
make sure there are 48 `x`s in the example ELEVENLABS_API_KEY
